### ISSUE TITLE
Error : object ‘items_bands’ not exported by 'namespace:rstac'

### ISSUE THREAD

**Issue by gse-cc-git** [mapme-initiative/mapme.vegetation#8]
Hello,
While trying to install `mapme.vegetation` with `remotes::install_github("mapme-initiative/mapme.vegetation")` I ran into the following error:
```
Error : object ‘items_bands’ not exported by 'namespace:rstac'
```

It appear that `rstac::item_bands` was replaced with `rstac::items_assets` since `rstac` version 0.9.1-5 (Released 2021-11-01).

My dirty hack is to install `rstac` version 0.9.1-4

```
devtools::session_info()
─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.2 (2022-10-31)
 os       Ubuntu 20.04.4 LTS
 system   x86_64, linux-gnu
 ui       RStudio
 language (EN)
 collate  fr_FR.UTF-8
 ctype    fr_FR.UTF-8
 tz       Europe/Paris
 date     2023-02-06
 rstudio  2022.12.0+353 Elsbeth Geranium (desktop)
 pandoc   NA
─ Packages ────────────────────────────────────────────────────
 package          * version    date (UTC) lib source
mapme.vegetation * 0.0.0.9010 2023-02-06 [1] Github (gse-cc-git/mapme.vegetation@a08a299)
rstac              0.9.2-2    2023-02-01 [1] CRAN (R 4.2.2)
```

**Comment by goergen95** [comment]
Thanks, well spotted! The conflicting line with the most recent version of rstac is found here:
https://github.com/mapme-initiative/mapme.vegetation/blob/0c4989244c52b8bda713484cbb1d56b5da728ca3/R/utility.R#L268

Would you mind open a PR?

**Comment by gse-cc-git** [comment]
Sure ! Will learn to :-)
